### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [SmeetaPatel/prj-rev-bwfs-dasmoto#6]
https://github.com/SmeetaPatel/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/style.css#L9-L28

You're repeating a lot of styles here. Extract the shared styles into a more general selector so that you can eliminate repetition from your code.

```css
* { 
  font-family: Helvetica;
}

h2 {
  font-size: 32px;
  color: white;
  font-weight: bold;
}

h3 {
  font-size: 20px;
  color: #6D6F6F;
}

// and so on
```
